#
# RSS-to-HTML
# Copyright (C) 2024
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

name: Build and Push Docker Image to Docker Hub

on:
  - push
  - pull_request

jobs:

  push_to_registry:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:

      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push the Docker image to registry
        uses: docker/build-push-action@v5
        with:
#          build-args: |
#            CI_COMMIT_SHA=$GITHUB_SHA
#            CI_COMMIT_REF_NAME=$GITHUB_REF
#            CI_PIPELINE_CREATED_AT=$(date --rfc-email)
          context: DockerFileFolder/
          push: true
          tags: 0.0.1
